# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: entigo-pipeline-plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build 
      run: ./mvnw install -q

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: entigo-pipeline-{{ github.run_number }}.hpi
        path: target/entigo-pipeline.hpi
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v{{ github.run_number }}-${{ github.ref }}
        release_name: Release v{{ github.run_number }}-${{ github.ref }}
        body: |
          TODO
        draft: true
        prerelease: true
