# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: entigo-pipeline-plugin

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build 
      run: ./mvnw install -q
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Get version
      run: |
        VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
        echo "::set-output name=version::$VERSION"
      id: get_version
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: entigo-pipeline-${{ steps.get_version.outputs.version }}${{ github.run_number }}.hpi
        path: target/entigo-pipeline.hpi
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ steps.get_version.outputs.version }}${{ github.run_number }}
        body: |
          TODO
        draft: true
        prerelease: true
    - name: Upload Release Artifact
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: target/entigo-pipeline.hpi
        asset_name: entigo-pipeline-${{ steps.get_version.outputs.version }}${{ github.run_number }}.hpi
        asset_content_type: application/octet-stream
